server:
  port: 8080
  servlet:
    application-display-name: srms
    context-path: /srms-api

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:srmsdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.shyftlabs.srms: DEBUG
    org.hibernate:
      SQL: DEBUG
      orm.jdbc.bind: TRACE

